### ISSUE TITLE
Pricing Module

### ISSUE THREAD

**Issue by mifatran** [JREastonMarks/COSC6353#6]
We need to implement pricing module, and I think it should be for event cost and sponsorship needed. We also need to connect it to reporting module for pricing report before and after each event.

**Comment by JREastonMarks** [comment]
Are you sure that it is a requirement? I don't remember reading anything else about that in the assignments.

**Comment by JREastonMarks** [comment]
Closing:
From Bryan (TA):
That is a holdover from previous courses. It is meant to be the reporting module that you implement for the final assignment.
