### ISSUE TITLE
Volunteer History Performance

### ISSUE THREAD

**Issue by mifatran** [JREastonMarks/COSC6353#7]
We need to implement Volunteer Performance Rating section only for Administrator's use on Volunteer History component to rate performance of a specific volunteer in a particular event.

**Comment by JREastonMarks** [comment]
We can probably add a new field to the match model that is rating.

**Comment by mifatran** [comment]
> We can probably add a new field to the match model that is rating.

Omg i forgot ab this lemme check real quick
